# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fu7ONUSOKT-HmT-EDKBLa2Wh8wIqCVgv
"""

def add(x,y):
    return x+y
def subtract(x,y):
    return x-y
def multiple(x,y):
    return x*y
def divisible(x,y):
    return x/y
print('select the operator')
print('1.Add')
print('2.Subtract')
print('3.Multiple')
print('4.Divide')
while True:
    choice =(input('enter choice (1/2/3/4):'))
    if choice in ('1','2','3','4'):
        num_1=float(input('enter the 1st number:'))
        num_2 = float(input('enter the 2st number:'))

        if choice == '1':
            print(num_1,'+',num_2,'=',add(num_1,num_2))
        elif choice == '2':
            print(num_1,'-',num_2,'=',subtract(num_1,num_2))
        elif choice == '3':
            print(num_1,'*',num_2,'=',multiple(num_1,num_2))
        elif choice == '4':
            print(num_1,'/',num_2,'=',divisible(num_1,num_2))
        next_calculation = input('lets do the next calculation?(yes/no):')
        if next_calculation == 'no':
            print('ok bye')
            break
    else:
        print('invalid input')

