# -*- coding: utf-8 -*-
"""calendar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fu7ONUSOKT-HmT-EDKBLa2Wh8wIqCVgv
"""

import calendar

year=int(input("enter the year:"))
month=int(input("enter the month in number:"))
print(calendar.month(year, month))

