# -*- coding: utf-8 -*-
"""Factorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rcySFVe9f1100icY7PM5M0APZ4ps_ZFs
"""

def fact(num):
  if num == 1:
    return num
  else:
    return num * fact(num - 1)

num =int(input('enter the number:'))
print(fact(num))

