# -*- coding: utf-8 -*-
"""Matplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NNVtkHtNUaHUdfoYDA1YS2nDOv2C5juK
"""

from matplotlib import pyplot as plt
from matplotlib import style

#           x       y
plt.plot([1,2,3],[4,5,1])

plt.show()



x=[5,8,10]
y=[12,16,6]

plt.plot(x,y)
plt.title('info')
plt.ylabel('Y axis')
plt.xlabel('X axis')
plt.show()



style.use('ggplot')

x=[5,8,10]
y=[12,16,6]
x2=[6,9,11]
y2=[6,15,7]

plt.plot(x,y,'g',label='line one',linewidth=5)
plt.plot(x2,y2,'c',label='line two',linewidth=5)
plt.title('Epic Info')
plt.ylabel('Y axis')
plt.xlabel('X axis')
plt.legend()
plt.grid(True,color='k')
plt.show()



#BAR

plt.bar([1,3,5,7,9],[5,2,7,8,2],label='Example one',color='y')
plt.bar([2,4,6,8,10],[8,6,2,5,6],label='Example one',color='g')

plt.legend()
plt.xlabel('Bar number')
plt.ylabel('bar height')

plt.title('info')
plt.show()



#HISTOGRAM

population_age=[22,55,62,45,21,22,34,42,42,4,99,102,110,120,121,122,130,111,115,112,80,75,65,54,44
                ,43,42,48]
bins=[0,10,20,30,40,50,60,70,80,90,100,110,120,130]

plt.hist(population_age,bins,histtype='bar',rwidth=.8,color='y')
plt.xlabel('X')
plt.ylabel('Y')

plt.title('Histogram')
plt.legend()
plt.show()



#SCATTER PLOT



x=[1,2,3,4,5,6,7,8]
 y=[5,2,4,2,1,4,5,2]

plt.scatter(x,y,label='skitscat',color='r')
plt.xlabel('X')
plt.ylabel('Y')

plt.title('Scatter Plot')
plt.legend()
plt.show()



#STACK PLOT

days=[1,2,3,4,5]
sleeping=[7,8,6,11,7]
eating=[2,3,4,3,2]
working=[7,8,7,2,2]
playing=[8,5,7,8,13]

plt.plot([],[],color='m',label='sleeping',linewidth=5)
plt.plot([],[],color='c',label='Eating',linewidth=5)
plt.plot([],[],color='r',label='Working',linewidth=5)
plt.plot([],[],color='k',label='Playing',linewidth=5)

plt.stackplot(days,sleeping,eating,working,playing,colors=['m','c','r','k'])

plt.xlabel('X')
plt.ylabel('Y')

plt.title('Stack Plot')
plt.legend()
plt.show()





#PIE CHART

slices=[7,2,2,13]
activities=['sleeping','eating','working','playing']
cols=['c','m','r','b']

plt.pie(slices,
        labels=activities,
        colors=cols,
        startangle=90,
        shadow=True,
        explode=(0,0.1,0,0),
        autopct='%1.1f%%')

plt.title('pie plot')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

#working with multiple plots

def f(t):
  return np.exp(-t)*np.cos(2*np.pi*t)

t1=np.arange(0.0,5.0,0.1)
t2=np.arange(0.0,5.0,0.02)

plt.subplot(211)
plt.plot(t1,f(t1),'bo',t2,f(t2))

plt.subplot(212)
plt.plot(t2,np.cos(2*np.pi*t2))
plt.show()

