# -*- coding: utf-8 -*-
"""Num summation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rcySFVe9f1100icY7PM5M0APZ4ps_ZFs
"""

def sum(a):
    num= (a+1)
    c=num*a
    b=c/2
    print(b)

a=int(input('enter the number:'))
sum(a)