# -*- coding: utf-8 -*-
"""Palindrom.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rcySFVe9f1100icY7PM5M0APZ4ps_ZFs
"""

while True:
  word = input('enter the word:')
  num=word[::-1]

  if word == num:
    print('Palindrom')
  else:
    print('Not Palindrom')
  word2 = input('do you want check another word(yes or no):')
  if word2 == 'no':
    print('ok bye')
    break

