# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/173qHEE-3RqHzT4begcfQh7GL52IIIKnM
"""

import pandas as pd
import numpy as np

s=pd.Series([1,2,3,4,5,6,np.nan,8,9])
s

d =pd.date_range('20200301',periods=10)
d

df=pd.DataFrame(np.random.randn(10,4),index=d,columns=['A','B','C','D'])
df

df1=pd.DataFrame({'A':[1,2,3,4],
                 'B':pd.Timestamp('20200301'),
                 'C':pd.Series(1,index=list(range(4)), dtype='float32'),
                 'D': np.array([5]*4, dtype='int32'),'E':pd.Categorical(['true','false','true','false']),
                  'F':'Edureka'})



df1=pd.DataFrame({'A':[1,2,3,4],
                 'B':pd.date_range('20200301',periods=4),
                 'C':pd.Series(1,index=list(range(4)), dtype='float32'),
                 'D': np.array([5]*4, dtype='int32'),
                 'E':pd.Categorical(['true','false','true','false']),
                  'F':'Edureka'})

df1

df1.dtypes

df.index

df.columns

df.to_numpy()

df.describe()

df.sort_index(axis=1, ascending=False)

df.sort_values(by='C')

df['C']

df[0:3]

df.loc[d[0]]

df.loc[:,['A','C']]

df.loc['20200301':'20200306',['D','C']]

df.loc['20200301',['D','C']] ##### or df.loc[d[0],['D','C']]

df.at[d[0],'D']

df.iloc[3]

df.iloc[3:5]

df.iloc[3:5,0:2]

df[df['A']>1]

df2=df.reindex(index=d[0:4], columns=list(df.columns) + ['E'])

df2.loc[d[0]:d[1],'E']=1

df2

df2.isnull()

df2.isnull().count()

df2.dropna()

df2.fillna(value=2)

#PANDAS OPERATION

df2.mean()

df2.mean(1)

s=pd.Series([1,2,3,np.nan,4,5,6,7,8,9],index=d).shift(2)

s

df.sub(s,axis='index')

df.apply(np.cumsum)

df.apply(lambda x:x.max() - x.min())

s.value_counts()

s = pd.Series(['edureka','python','colab',np.nan,'cricket','india'])

s.str.lower()

s.str.upper()

df = pd.DataFrame(np.random.randn(10,4))

df

df2=[df[:3],df[3:7],df[7:]]

df2

pd.concat(df2)

left=pd.DataFrame({'A':[1,2],'B':[3,4]})

right=pd.DataFrame({'A':[5,6],'B':[7,8]})

left

right

pd.merge( left, right, on='B')

df

df.groupby(2).sum()





my_tuple = list(zip(*[[1,2,3,4,5,17,18,19],[11,12,13,6,7,8,9,10]]))
 index = pd.MultiIndex.from_tuples(my_tuple, names=['First','Second'])
 df = pd.DataFrame(np.random.randn(8,2),index=index,columns=['A','B'])

df2=df[:4]
df2

df2.stack()

df.unstack()

df=pd.DataFrame({'a })